### PR TITLE
UBFIX on 7th iteration of HandleSendFailure's loop

### PR DESCRIPTION
**Pull request by PokeCodec**
Here is a UB found entirely on my own. On the 7th iteration, sResendBlock16[7] will be written to. The problem is that this is beyond the array. So I added a UBFIX
## **Discord contact info**

Shoomer#2702

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
Your conditional is backwards. This doesn't match.

**Comment by PokeCodec** [comment]
Fixed

**Comment by aaaaaa123456789** [comment]
It seems like old habits die hard — you keep force-pushing, even after being told many times not to. If you want people to review your changes, please follow these simple guidelines:

1. Keep your PRs related to a single topic. Don't introduce "bonus" changes to nearby code; open a new PR for them afterwards.
2. Don't force-push on top of previous changes. If you need to rebase, do it at the end; a small PR like this one doesn't need periodic rebasings. If you need to fix mistakes from previous commits, just commit on top; the PR can be squashed on merge if needed. Force pushes make it incredibly hard to keep track of changes when reviewing the PR.
3. Ensure that the changes you introduce in a PR are related to one another and comprise one cohesive set of changes. If there are unrelated changes you want to make, just open additional PRs for them.

Please try to adhere to those guidelines from now on, as it will allow people to review your PRs accordingly.

**Comment by GriffinRichards** [comment]
This was merged incorrectly, it now contains duplicates of commits already in the repo. If you'd like please reopen with only the relevant new commits

**Pull request closed without merging**
