### PR TITLE
Match sub_819A080

### PR DESCRIPTION
**Pull request by pi1024e**
I, Rose, would like to propose using the match Shoomer wrote for this one unused function so that others can focus on the last nonmatchings. If you want to close without merge, I find no fault in you. This is my only contribution.

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
The problem with this change is that it has an "area of effect". The non-matching is at the end, but _the whole function_ has changed. How much of this is strictly necessary for matching?

**Comment by PikalaxALT** [comment]
There is a strong chance that this conflicts with #1189

**Comment by pi1024e** [comment]
> The problem with this change is that it has an "area of effect". The non-matching is at the end, but _the whole function_ has changed. How much of this is strictly necessary for matching?

It's in the end of a loop, where most changes are anyway

**Comment by aaaaaa123456789** [comment]
And this is why we've been rejecting all your "removals of unsanitary changes" PRs. They all keep many style changes that are not necessary.

**Comment by pi1024e** [comment]
All changes here were necessary.

**Comment by aaaaaa123456789** [comment]
What happens if you remove the cast on ilne 2040?

**Comment by pi1024e** [comment]
Everything is fine.

**Comment by aaaaaa123456789** [comment]
Then that change wasn't strictly necessary, was it? And this is the game I don't want to have to play on every PR.

**Comment by pi1024e** [comment]
Only needed changes are here

**Comment by pi1024e** [comment]
You can’t fire me; I quit this project.

**Pull request closed without merging**
