### PR TITLE
Fix bad sigs

### PR DESCRIPTION
**Pull request by Phlosioneer**
Fix GetMonData and GetBoxMonData to typecheck correctly using the magic of _macros_.

### CODE REVIEW

**Comment by huderlem** [comment]
I don't think this is an improvement.

**Comment by huderlem** [comment]
The type-checking is an improvement, but I don't want `GetMonData_2`s floating around everywhere.

**Comment by Phlosioneer** [comment]
But it's already found bugs. Would a different name be better?

**Comment by Phlosioneer** [comment]
*_2 is the standard way we deal with duplicate function definitions in this repo.

**Comment by huderlem** [comment]
One idea is to change the 3-arg version of `GetMonData` to `BufferMonData`.  And then the 2-arg version can remain `GetMonData`.

**Comment by Phlosioneer** [comment]
Sure, as long as it's typechecked I'm happy.

**Comment by Phlosioneer** [comment]
How does `GetMonData` for 2 and `GetMonDataExtended` for 3 sound?

**Comment by Phlosioneer** [comment]
Get*MonData => Get*MonDataExtended
Get*MonData_2 => Get*MonData

**Comment by huderlem** [comment]
Closing per offline discussion.  Bug fixes exposed by type checking will be in a followup PR.

**Pull request closed without merging**
