### PR TITLE
Update createsprite macro and rename BANK to BATTLER

### PR DESCRIPTION
**Pull request by garakmon**

### CODE REVIEW

**Comment by DizzyEggg** [comment]
Eh, I dont really like making the defines longer than necessary.

Can't ANIM_TARGET and such stay the way they already are?

**Comment by garakmon** [comment]
they could I guess I just changed them to match ruby

**Comment by DizzyEggg** [comment]
Ruby can change them to match pokeemerald's 😃

**Comment by garakmon** [comment]
why no build

**Pull request merged**
