### PR TITLE
Opponent Constants

### PR DESCRIPTION
**Pull request by Mother-Of-Dragons**

### CODE REVIEW

**Comment by camthesaxman** [comment]
Thanks! Can you please move this file to include/constants/opponents.h, and also add a new line at the end of the file? I am about to move all of these constants files into include/constants to reorganize the headers.

**Comment by Mother-Of-Dragons** [comment]
Apologies, didn't mean to send the entire folder! Hope it's better now.

**Comment by camthesaxman** [comment]
Can you please merge the upstream pret branch into this, so GitHub will show the correct changes when merging?

**Comment by Diegoisawesome** [comment]
Hey, just wanted to know if there was an update on this.

**Pull request merged**
