### PR TITLE
Switch to syntax-unified

### PR DESCRIPTION
**Pull request by PokeCodec**
We have been writing all our asm in unified syntax. However, by default, gcc outputs the old syntax. -masm-unified-syntax ensures that the asm it outputs are syntax unified

### CODE REVIEW

**Comment by PokeCodec** [comment]
Note: I did not change the asm for copyglyph since I have a different pr for that anyway, so accept the copyglyph pr first, and then I will fix and squash this one.

**Comment by GriffinRichards** [comment]
I'm not really convinced any of this is necessary

**Comment by PokeCodec** [comment]
considering syntax unified is the standard, it makes sense that ALL the asm is in the newer syntax, because having some in the legacy syntax but others in the unified syntax isn't good style.

**Comment by kiliwily** [comment]
This pull request need to be fixed.

**Comment by PokeCodec** [comment]
I merged all changes into one convenient PR

**Pull request closed without merging**
