### PR TITLE
Remove Travis badge

### PR DESCRIPTION
**Pull request by SatoMew**
## Description
This PR removes a leftover from the switch to GitHub Actions.

## **Discord contact info**
SatoMew#8484

### CODE REVIEW

**Comment by GriffinRichards** [comment]
Why the other changes?

**Comment by SatoMew** [comment]
> Why the other changes?

The hash one is just for clarity while the support links were made more prominent to follow in the spirit of #1274, which mentions them a lot.

**Comment by GriffinRichards** [comment]
They seem less prominent to me now, they had their own bold header before.

**Comment by ExpoSeed** [comment]
an alternative would be to reorder the sections so contacts comes before see also

**Comment by SatoMew** [comment]
Would it be OK to bolden that particular text instead? I removed the header because it seemed wasteful.

**Comment by GriffinRichards** [comment]
It really seems fine to me where it is, I don't think it's hard to notice

**Comment by huderlem** [comment]
I think the README is fine as it is.  Swapping the Travis badge for the GitHub Actions badge is all that should change.

**Comment by SatoMew** [comment]
@GriffinRichards @huderlem Done!

**Pull request merged**
