### PR TITLE
Use SCRCMD_DEF define from firered

### PR DESCRIPTION
**Pull request by PikalaxALT**

### CODE REVIEW

**Comment by DizzyEggg** [comment]
Thats clever, I like it

**Comment by huderlem** [comment]
I'm not convinced this is an improvement.  It obscures the function signature, and the readability isn't any better, in my opinion.

**Comment by SBird1337** [comment]
I'd agree with @huderlem - What's the point in doing that, apart from having a few less characters?

**Comment by Diegoisawesome** [comment]
Agreed, I don't like this change for the same reasons stated above.

**Comment by PikalaxALT** [comment]
Okay, I'll close this and expand the macro in firered.

**Pull request closed without merging**
