### PR TITLE
Changed mon front and back coordinates from hex to decimal so they're easier to edit.

### PR DESCRIPTION
**Pull request by AsparagusEduardo**

### CODE REVIEW

**Comment by huderlem** [comment]
Changing `.size` to decimal makes it much harder, since the high and low nybbles are the dimensions.

**Comment by AsparagusEduardo** [comment]
I'll revert it then, one sec.

**Comment by huderlem** [comment]
It's possible that `.size` is actually a bitfield with two 4-bit values, but I haven't ever attempted to see if it matches that way.

**Comment by GriffinRichards** [comment]
> It's possible that `.size` is actually a bitfield with two 4-bit values, but I haven't ever attempted to see if it matches that way.

I believe I've tried that in the past and it doesn't match

**Comment by GriffinRichards** [comment]
Check this over again, you missed a number of `y_offset`s that are still hex values

**Pull request merged**
