### PR TITLE
Made Types and Egg Groups into arrays

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Had issues pushing new commits to #1821, so made this new one.

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by GriffinRichards** [comment]
Were you still planning on making this change?
https://github.com/pret/pokeemerald/pull/1821#issuecomment-1324204194

**Comment by AsparagusEduardo** [comment]
> Were you still planning on making this change? [#1821 (comment)](https://github.com/pret/pokeemerald/pull/1821#issuecomment-1324204194)

Oh right, I forgot about

**Comment by AsparagusEduardo** [comment]
> Were you still planning on making this change? [#1821 (comment)](https://github.com/pret/pokeemerald/pull/1821#issuecomment-1324204194)

Oh right, I forgot about that. Let me do it real quick

**Comment by AsparagusEduardo** [comment]
Ready

**Pull request merged**
