### PR TITLE
Remove dead prototypes

### PR DESCRIPTION
**Pull request by RickPickle2**
I am unfamiliar with this project but would like to contribute.
So i remove the dead prototypes first.

### CODE REVIEW

**Comment by coltongit** [comment]
Are these actually used in any way anywhere in the project?

**Comment by LOuroboros** [comment]
> Are these actually used in any way anywhere in the project?

Nope. Those functions are declared in `gflib/sprite.h` and never used at all.

**Comment by coltongit** [comment]
> > Are these actually used in any way anywhere in the project?
> 
> Nope. Those functions are declared in `gflib/sprite.h` and never used at all.

Exactly what I was able to come up with with a simple VSCode search.

**Comment by coltongit** [comment]
Looks good to me! This one's ready to merge

**Comment by coltongit** [comment]
Companion PR at https://github.com/pret/pokefirered/pull/513, seems to be a leftover from pokeruby

**Pull request closed without merging**
