### PR TITLE
Made Types and Egg Groups into arrays

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Figured that making types and egg groups into arrays made sense after seeing the same being done to abilities

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by GriffinRichards** [comment]
Why is this preferable? They're never treated as arrays (i.e. they're never looped over) so it's not as if it really improves the process of adding additional elements to any of these. In a similar vein, I don't think we should have array size constants that are never used (all this does is move the size to a different file, which if anything makes it harder to edit)

**Comment by AsparagusEduardo** [comment]
The `abilities` field isn't looped over either, and yet it was made into an array.

```
29 results - 7 files

src\battle_ai_script_commands.c:
  1381  
  1382:         if (gSpeciesInfo[gBattleMons[battlerId].species].abilities[0] != ABILITY_NONE)
  1383          {
  1384:             if (gSpeciesInfo[gBattleMons[battlerId].species].abilities[1] != ABILITY_NONE)
  1385              {

  1387                  if (Random() & 1)
  1388:                     AI_THINKING_STRUCT->funcResult = gSpeciesInfo[gBattleMons[battlerId].species].abilities[0];
  1389                  else
  1390:                     AI_THINKING_STRUCT->funcResult = gSpeciesInfo[gBattleMons[battlerId].species].abilities[1];
  1391              }

  1393              {
  1394:                 AI_THINKING_STRUCT->funcResult = gSpeciesInfo[gBattleMons[battlerId].species].abilities[0]; // It's definitely ability 1.
  1395              }

  1398          {
  1399:             AI_THINKING_STRUCT->funcResult = gSpeciesInfo[gBattleMons[battlerId].species].abilities[1]; // AI can't actually reach this part since no pokemon has ability 2 and no ability 1.
  1400          }

  1429          }
  1430:         else if (gSpeciesInfo[gBattleMons[battlerId].species].abilities[0] != ABILITY_NONE)
  1431          {
  1432:             if (gSpeciesInfo[gBattleMons[battlerId].species].abilities[1] != ABILITY_NONE)
  1433              {
  1434                  u8 abilityDummyVariable = ability; // Needed to match.
  1435:                 if (gSpeciesInfo[gBattleMons[battlerId].species].abilities[0] != abilityDummyVariable
  1436:                 && gSpeciesInfo[gBattleMons[battlerId].species].abilities[1] != abilityDummyVariable)
  1437                  {
  1438:                     ability = gSpeciesInfo[gBattleMons[battlerId].species].abilities[0];
  1439                  }

  1446              {
  1447:                 ability = gSpeciesInfo[gBattleMons[battlerId].species].abilities[0];
  1448              }

  1451          {
  1452:             ability = gSpeciesInfo[gBattleMons[battlerId].species].abilities[1]; // AI can't actually reach this part since no pokemon has ability 2 and no ability 1.
  1453          }

src\battle_ai_switch_items.c:
  201          if (GetMonData(&party[i], MON_DATA_ABILITY_NUM) != 0)
  202:             monAbility = gSpeciesInfo[species].abilities[1];
  203          else
  204:             monAbility = gSpeciesInfo[species].abilities[0];
  205  

  399          if (GetMonData(&party[i], MON_DATA_ABILITY_NUM) != 0)
  400:             monAbility = gSpeciesInfo[species].abilities[1];
  401          else
  402:             monAbility = gSpeciesInfo[species].abilities[0];
  403  

src\battle_dome.c:
  2754      defType2 = gSpeciesInfo[targetSpecies].types[1];
  2755:     defAbility = gSpeciesInfo[targetSpecies].abilities[0];
  2756      moveType = gBattleMoves[move].type;

  5206                  if (var & 1)
  5207:                     targetAbility = gSpeciesInfo[targetSpecies].abilities[1];
  5208                  else
  5209:                     targetAbility = gSpeciesInfo[targetSpecies].abilities[0];
  5210  

src\battle_pike.c:
  1142  
  1143:     if (gSpeciesInfo[wildMons[headerId][pikeMonId].species].abilities[1])
  1144          abilityNum = Random() % 2;

src\battle_pyramid.c:
  1383      default:
  1384:         if (gSpeciesInfo[wildMons[id].species].abilities[1])
  1385          {

src\battle_script_commands.c:
  9570              if (GetMonData(&gPlayerParty[i], MON_DATA_ABILITY_NUM))
  9571:                 ability = gSpeciesInfo[species].abilities[1];
  9572              else
  9573:                 ability = gSpeciesInfo[species].abilities[0];
  9574  

  9593              if (GetMonData(&gPlayerParty[i], MON_DATA_ABILITY_NUM))
  9594:                 ability = gSpeciesInfo[species].abilities[1];
  9595              else
  9596:                 ability = gSpeciesInfo[species].abilities[0];
  9597  

src\pokemon.c:
  2288  
  2289:     if (gSpeciesInfo[species].abilities[1])
  2290      {

  4497      if (abilityNum)
  4498:         gLastUsedAbility = gSpeciesInfo[species].abilities[1];
  4499      else
  4500:         gLastUsedAbility = gSpeciesInfo[species].abilities[0];
  4501  
```

**Comment by GriffinRichards** [comment]
> The abilities field isn't looped over either, and yet it was made into an array.
Yes and I would make the same argument against having the abilities as an array. Regardless I don't think "a different field is like this" is a compelling argument to change these to arrays.

**Comment by AsparagusEduardo** [comment]
Mainly I was thinking on reducing the amount of lines while maintaining the amount of information.
I will concede that the array constants aren't needed, and will remove those.

**Pull request closed without merging**
