### PR TITLE
Created more enums, made more macros, and documented some functions

### PR DESCRIPTION
**Pull request by PokeCodec**
Until I manage to finish fixing the fakematches, I thought I'd send in a PR with some more documentation done with macros.

### CODE REVIEW

**Comment by PokeCodec** [comment]
Ready for review!

**Comment by PikalaxALT** [comment]
90% of the PR is unnecessary and downright head-scratching changes. Vote reject.

**Comment by PokeCodec** [comment]
I will revert the mere refactoring changes then. Hopefully then the meaningful changes will become clear

**Comment by PokeCodec** [comment]
Going to close this since I don't know what to do at this point.

**Pull request closed without merging**
