### PR TITLE
Added POKEMART_LIST_END to avoid users accidentally removing it

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Previously, because it had the `ITEM_`/`DECOR_` prefix, users would mistakenly remove it from their custom mart lists.
This should hopefully aleviate the issue.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by GriffinRichards** [comment]
I think this could be much more useful not as an alias of `ITEM_NONE`, given this isn't that much more visually distinct from the end of the list, and it's very unlikely anyone would redefine it. It might be more useful to define something like this:
```asm
.macro POKEMART_LIST_END
    .2byte ITEM_NONE
    release
    end
.endm
```

So that A. it would be more visually distinct from the end of the list:
```asm
    .2byte ITEM_CARBOS
    .2byte ITEM_HP_UP
    POKEMART_LIST_END
```

and B. so the unnecessary `release` and `end` are hidden and can be removed by editing one location.

**Comment by AsparagusEduardo** [comment]
Good idea! Since it's gonna be a macro, would `pokemartlistend` be a better name for it?

**Comment by GriffinRichards** [comment]
> Since it's gonna be a macro, would pokemartlistend be a better name for it?

Up to you

**Comment by AsparagusEduardo** [comment]
13-month PR comeback babyyy!

**Pull request merged**
