### PR TITLE
Added TYPE_ICON_SPRITE_COUNT to Summary documentation

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Comment by sphericalice** [comment]
Wouldn't it be more idiomatic as `i <= SPRITE_ARR_ID_TYPE + MAX_MON_MOVES`? Assuming that matches

**Comment by AsparagusEduardo** [comment]
> Wouldn't it be more idiomatic as `i <= SPRITE_ARR_ID_TYPE + MAX_MON_MOVES`? Assuming that matches

`MAX_MON_MOVES` is 4, not 5. And even then, it would make more sense to modify `SPRITE_ARR_ID_MOVE_SELECTOR1`'s enum to `SPRITE_ARR_ID_MOVE_SELECTOR1 = SPRITE_ARR_ID_TYPE + MAX_MON_MOVES + 1`,

**Comment by sphericalice** [comment]
Actually I think it should be `i < MAX_MON_MOVES + 1`. The 5th is the move that displays at the bottom when you're trying to teach / replace a move. The 5 refers to the number of move type sprites, it isn't related to the move selector (except insofar as it is the next sprite ID after the 5 move type sprites).

**Comment by AsparagusEduardo** [comment]
Are you just ignoring `SPRITE_ARR_ID_TYPE` now?

**Comment by sphericalice** [comment]
Sorry, yeah, i < SPRITE_ARR_ID_TYPE + MAX_MON_MOVES + 1.

**Comment by AsparagusEduardo** [comment]
> Sorry, yeah, i < SPRITE_ARR_ID_TYPE + MAX_MON_MOVES + 1.

But again, that iteration is supposed to loop through all the type icon sprite IDs, meaning that it would be more correct to have it defined as it's stopping at the first non-type icon sprite ID, aka `SPRITE_ARR_ID_MOVE_SELECTOR1`

**Comment by sphericalice** [comment]
Hmm I think it is a matter of preference but I think would argue that my version is more descriptive of what's actually happening as if someone rearranges those enums the loop would still be descriptive of precisely what is intended e.g. create sprites for each move slot's type icon, of which there are 4 (MAX_MON_MOVES) plus the 1 extra for the move being learned.

**Comment by AsparagusEduardo** [comment]
The way I see it is that in case someone where to try to add a new type icon (like with Tera Types) they could easily change the enum to
```diff
enum
{
    SPRITE_ARR_ID_MON,
    SPRITE_ARR_ID_BALL,
    SPRITE_ARR_ID_STATUS,
-   SPRITE_ARR_ID_TYPE, // 2 for mon types, 5 for move types(4 moves and 1 to learn), used interchangeably, because mon types and move types aren't shown on the same screen
-   SPRITE_ARR_ID_MOVE_SELECTOR1 = SPRITE_ARR_ID_TYPE + MAX_MON_MOVES + 1, // 10 sprites that make up the selector
+   SPRITE_ARR_ID_TYPE, // 3 for mon types, 5 for move types(4 moves and 1 to learn), used interchangeably, because mon types and move types aren't shown on the same screen
+   SPRITE_ARR_ID_MOVE_SELECTOR1 = SPRITE_ARR_ID_TYPE + MAX_MON_MOVES + 2, // 10 sprites that make up the selector
    SPRITE_ARR_ID_MOVE_SELECTOR2 = SPRITE_ARR_ID_MOVE_SELECTOR1 + MOVE_SELECTOR_SPRITES_COUNT,
    SPRITE_ARR_ID_COUNT = SPRITE_ARR_ID_MOVE_SELECTOR2 + MOVE_SELECTOR_SPRITES_COUNT
};
```
And add this to `SetMonTypeIcons`
```diff
        SetTypeSpritePosAndPal(gSpeciesInfo[summary->species].type1, 120, 48, SPRITE_ARR_ID_TYPE);
        if (gSpeciesInfo[summary->species].type1 != gSpeciesInfo[summary->species].type2)
        {
            SetTypeSpritePosAndPal(gSpeciesInfo[summary->species].type2, 160, 48, SPRITE_ARR_ID_TYPE + 1);
            SetSpriteInvisibility(SPRITE_ARR_ID_TYPE + 1, FALSE);
        }
        else
        {
            SetSpriteInvisibility(SPRITE_ARR_ID_TYPE + 1, TRUE);
        }
+       SetTypeSpritePosAndPal(summary->teraType, 200, 48, SPRITE_ARR_ID_TYPE + 2);
```

**Comment by AsparagusEduardo** [comment]
Forgot to post the gif
tera2

**Comment by GriffinRichards** [comment]
I agree that writing `i = SPRITE_ARR_ID_TYPE; i < SPRITE_ARR_ID_MOVE_SELECTOR1` is confusing, because this is unrelated to the sprite for the move selector.

If you want that 5 to be used in multiple places, make a define for it. Add a `#define NUM_TYPE_SPRITES (MAX_MON_MOVES + 1)`, and do `SPRITE_ARR_ID_TYPE + NUM_TYPE_SPRITES` in the enum and the loop.

As an aside, your example with the gif is incorrect. You wouldn't need to add space for an additional sprite (there's space for 5 sprites, and it's used either by the 2 pokemon types or the 5 move types, so you'd already have room for 3 pokemon type sprites)

**Comment by AsparagusEduardo** [comment]
> If you want that 5 to be used in multiple places, make a define for it. Add a `#define NUM_TYPE_SPRITES (MAX_MON_MOVES + 1)`, and do `SPRITE_ARR_ID_TYPE + NUM_TYPE_SPRITES` in the enum and the loop.
> 
> As an aside, your example with the gif is incorrect. You wouldn't need to add space for an additional sprite (there's space for 5 sprites, and it's used either by the 2 pokemon types or the 5 move types, so you'd already have room for 3 pokemon type sprites)

You're right. Do you want me to take the chance to get rid of the `PSS_` prefixes?

**Comment by GriffinRichards** [comment]
> Do you want me to take the chance to get rid of the PSS_ prefixes?
That's ok, they can be for another time (a lot of them should be rewritten to a more concise name beyond just removing the `PSS_` prefix)

**Comment by AsparagusEduardo** [comment]
Ready.

**Pull request merged**
