### PR TITLE
decompile item_use

### PR DESCRIPTION
**Pull request by golemgalvanize**

### CODE REVIEW

**Comment by Diegoisawesome** [comment]
[174] `const u8 *str`

**Comment by Diegoisawesome** [comment]
[231] Is the temp var really needed?

**Comment by Diegoisawesome** [comment]
[378-380] Remove the spaces around the arrows

**Comment by Diegoisawesome** [comment]
[882-884] Remove curly braces

**Comment by Diegoisawesome** [comment]
[1103 - 1105] Add curly braces

**Comment by golemgalvanize** [comment]
the temp var for data? yeah it should be needed since that's what normally happens when gTasks + 0x8 is loaded

**Pull request merged**
