### PR TITLE
Standardize Object Event naming

### PR DESCRIPTION
**Pull request by GriffinRichards**
NOTE: Should break porymap compatibility

SUMMARY:
This PR standardizes the nomenclature for object events to fit as part of the larger event group (e.g. warp events, coord events, etc). 

For the purposes of file organization, files/filepaths (and their include guards) retain the old `event_object` name scheme. The following files changed names:
`event_obj_lock` --> `event_object_lock`
`bg_event_constants` --> `event_bg`
`event_object_movement_constants` --> `event_object_movement`
`field_object_palette_*.pal` --> `event_object_palette_*.pal`

The following directories changed names:
`graphics/event_objects` --> `graphics/object_events`
`src/data/field_event_obj` --> `src/data/object_event`

The following replacements are made throughout the repo (note that if this PR is being reproduced with a script, file paths/include guards will need to be excluded/fixed to keep the names listed above)

| Old name | New name |
| ------------- | ------------- |
| EventObject | ObjectEvent |
| EventObj | ObjEvent |
| eventObject | objectEvent |
| eventObj | objEvent |
| EVENT_OBJECT | OBJECT_EVENT |
| EVENT_OBJ | OBJ_EVENT |
| EVENTOBJ | OBJEVENT |
| event object | object event |
| event_object | object_event |
| field_event_obj | object_event |
| mapObject | objectEvent |

### CODE REVIEW

**Comment by GriffinRichards** [comment]
Leaves file/directory names as `event_object` as discussed, and also doesn't touch berry_fix because that whole folder is a mess of outdated names already and should be fixed separately later

**Comment by garakmon** [comment]
WIP / being updated
some suggestions (while I'm doing firered work):
- rename `include/event_obj_lock.h` to `include/event_object_lock.h`

**Comment by GriffinRichards** [comment]
> * rename `include/event_obj_lock.h` to `include/event_object_lock.h`
Added

**Comment by GriffinRichards** [comment]
Might be worth squashing this when it's all set so there aren't 2 dozen merge commits in the history

**Comment by GriffinRichards** [comment]
It occurs to me it might be possible for Travis to miss a build failure on this PR after #953 is merged, assuming it isn't rerun. #953 adds a few `255` --> `EVENT_OBJ_ID_PLAYER`, which this wouldnt have renamed to `OBJ_EVENT_ID_PLAYER` and wont conflict. This should be checked to build on the current master before merging

**Pull request merged**
