### PR TITLE
Remove Fakematch and add documentation

### PR DESCRIPTION
**Pull request by SleepyDweams**
## Description

Removed fake match in battle_factory and added a description for how selection works

### CODE REVIEW

**Comment by SaarthakMohan** [comment]
uh oh travis fails

**Comment by ExpoSeed** [comment]
uh oh travis fails

reminder to use `make compare` to test matching rather than opening prs to test matching

**Comment by PokeCodec** [comment]
It was a really stupid mistake of keeping the check in there. For some reason that was added back despite the make compare initially passing.

**Comment by PokeCodec** [comment]
Ready to check

**Pull request closed without merging**
