### PR TITLE
Install libpng using pacman instead of manual build for msys2

### PR DESCRIPTION
**Pull request by laqieer**
## Description
It is troublesome and unnecessary to build it from source.

## **Discord contact info**
琪姬#1373

### CODE REVIEW

**Comment by GriffinRichards** [comment]
This looks fine to me, but I don't use msys2 so I don't know if there was a reason we were building libpng from source in the first place, i.e. if there will be users for whom this doesn't work. Otherwise I assume this was just overlooked or not an option at the time.

**Comment by laqieer** [comment]
It works fine for me. I didn't modify msys2.
[package homepage](https://packages.msys2.org/base/mingw-w64-libpng)
It is easy to find with search command.
```
$ pacman -Ss libpng
mingw32/mingw-w64-i686-libpng 1.6.37-6
    A collection of routines used to create PNG format graphics (mingw-w64)
mingw64/mingw-w64-x86_64-libpng 1.6.37-6 [installed]
    A collection of routines used to create PNG format graphics (mingw-w64)
ucrt64/mingw-w64-ucrt-x86_64-libpng 1.6.37-6
    A collection of routines used to create PNG format graphics (mingw-w64)
clang64/mingw-w64-clang-x86_64-libpng 1.6.37-6
    A collection of routines used to create PNG format graphics (mingw-w64)
dkp-libs/3ds-libpng 1.6.37-1 (3ds-portlibs)
    PNG format graphic files library (for Nintendo 3DS homebrew development)
dkp-libs/armv4t-libpng 1.6.37-1 (armv4t-portlibs)
    PNG format graphic files library (for armv4t homebrew development)
dkp-libs/nds-libpng 1.6.37-1 (nds-portlibs)
    PNG format graphic files library (for Nintendo NDS homebrew development)
dkp-libs/ppc-libpng 1.6.37-1 (ppc-portlibs)
    PNG format graphic files library (for Nintendo Gamecube/Wii homebrew
    development)
dkp-libs/switch-libpng 1.6.37-1 (switch-portlibs)
    PNG format graphic files library (for Nintendo Switch homebrew development)
```
Users for whom this doesn't work are supposed to describe their problem in detail for us to help.
For example:
- If they are confused with the package naming, read [this](https://www.msys2.org/docs/package-naming/).
- If search command gives no results, they should update the package database with `pacman -Syu`. Read [this](https://www.msys2.org/).

It helps for them to provide more information.

**Comment by GriffinRichards** [comment]
Yes, I'm just wondering aloud if there was any reason we had been suggesting to build it from source. Like I said I don't use msys2, I'll leave this for someone who does.

**Comment by LOuroboros** [comment]
> Yes, I'm just wondering aloud if there was any reason we had been suggesting to build it from source. Like I said I don't use msys2, I'll leave this for someone who does.

Knowing that Lucky took a lot of inspiration from my own guides, I'd like to clarify that in my own guide about building these projects with MSys2 I've been suggesting to build libpng from the source because it was the only way I personally knew to get it installed on an MSys2 environment *(taught to me by UltimaSoul)*, and I never really bothered looking for an alternative or a better option at the time. I just rolled with the first option that worked; building from the source.

If this alternative works the same, then as a user, I think it's a much better option, as it looks less tedious 👍

**Comment by GriffinRichards** [comment]
Per Kurausukun: 
> We used to build libpng from source for dkp msys2 specifically because dkp-pacman didn't have it. Recent updates have added it to the packages

**Pull request merged**
