### PR TITLE
Summary screen macros

### PR DESCRIPTION
**Pull request by Phlosioneer**
Minor improvements. I might have missed some places that need macros.

### CODE REVIEW

**Comment by huderlem** [comment]
2 thoughts:

I think these are not needed:
```
#define PSS_CHANGE_NEXT 1
#define PSS_CHANGE_PREV -1
```

I'd prefer `sMonSummaryScreen` instead of `sMonSummaryScreenData`.

Also, the build is broken.

**Comment by Phlosioneer** [comment]
This PR is updated.

**Comment by huderlem** [comment]
The summary screen struct's name was not changed, as stated in the commit message.  Also there is some spacing issues with find-replace:
`delta == -1&&`

**Comment by Phlosioneer** [comment]
This PR is updated. I actually did the rename this time! I hope.

**Pull request merged**
