### PR TITLE
BUGFIX for the aspect ratio of the Pokémon logo on the title screen

### PR DESCRIPTION
**Pull request by pkmnsnfrn**
* Implemented https://github.com/pret/pokeemerald/wiki/Fixing-the-aspect-ratio-of-the-Pok%C3%A9mon-logo-on-the-title-screen with permission from @meejle.

**Before** &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   **After**

 

I am pkmnsnfrn on Discord.

### CODE REVIEW

**Comment by GriffinRichards** [comment]
This seems to me too subjective a change to include by default, our `BUGFIX`s should be unambiguous solutions (I'm not even sure I agree this is a bug, but that's besides the point). Anyone who cares about this might care equally about the other minor changes it makes to the appearance, like the highlight inside the "P" disappearing or the changes to the black outline.

**Comment by GriffinRichards** [comment]
That's a sensible definition of `BUGFIX`. I don't agree that they almost certainly meant to use the logo in this PR as opposed to the one in-game. I grabbed an official logo online and compared it to the in-game asset; they seem reasonably the same to me:

pokemon_logo


But either way, I think we should avoid including fixes that involve making subjective decisions like for graphic design.

**Comment by pkmnsnfrn** [comment]
That gif is fascinating and very helpful! And I think "no graphic decisions" is more than fair.

cc @meejle

**Comment by meejle** [comment]
I don't particularly care about this, but someone messaged me about it in Discord (in August, but I rarely use it), but I've left the server since then and it won't let me reply to them. 🤷‍♂️

Just didn't want these comparison GIFs to go to waste. I would've thought it was fairly obvious just by looking, but here you go...

original
Original title screen with official logo overlaid

corrected
My version with official logo overlaid

comparison
Comparison of both, just so you know I'm not doing anything funky with the official logo

I'm not even into ROM hacking any more, and your philosophy about graphical changes seems sound, but at least y'all know what I mean now. 😅

**Pull request closed without merging**
