### PR TITLE
French

### PR DESCRIPTION
**Pull request by Arlequiin**
## Description
Translated items, moves, pokémon and abilities names

## **Discord contact info**
Arlequiin#1853

### CODE REVIEW

**Comment by atsen-dev** [comment]
Anyone know why this PR was closed ? No way to make build and specify a language ?

**Comment by atsen-dev** [comment]
Is your work done or not ? I'm searching a french decompilation of this game to try something

**Comment by GriffinRichards** [comment]
No this repo only builds the English version of Emerald. The author opened this PR by mistake. The branch they opened it from has an in-progress French version.

**Comment by Arlequiin** [comment]
Here is the repo if you want to use french decomp, work is almost done, the
rom matches with the original for 99.9% (Pokecreator made a script to get
the matching percentage)
https://github.com/DizzyEggg/pokeemerald/tree/french

**Pull request closed without merging**
